# Generated by Django 5.1.7 on 2025-04-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('encoding', models.BinaryField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='unknown_faces/')),
            ],
        ),
    ]
