# Generated by Django 5.1.7 on 2025-04-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0002_unknownperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='unknownperson',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
