# Generated by Django 5.1.7 on 2025-04-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0003_employeelogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
